variables:
  GLOBAL_VAR: "A global variable"
  
image: ${AF_CI_IMAGE}

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

## Check if we can build aar file on every push or when opening an MR from a release branch into master
build:
  stage: build
  rules:
    ## on every push push or when opening an MR from a release branch into master
    - if: '$CI_PIPELINE_SOURCE == "push" || ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^releases\/\d+.x.x\/\d+.\d+.x\/(\d+.\d+.\d+)-(rc\d+)/)'
  trigger:
    include:
      - project: 'mobile/android-child-pipelines'
        ref: 'master'
        file: 'build_adobe_aar.yml
'
